<<<<<<< HEAD
# name: Conda Environment Check

on: [push, pull_request]

=======
name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
>>>>>>> 8a19fe28c464fba972bdc5d3c347257a851a2d1c
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: stats_env
    - name: Verify Conda Environment
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Run Tests
      shell: bash -l {0}
      run: |
        pytest  # Replace with your project’s test command

